#.travis.yml

sudo: required
dist: trusty

language: node_js
node_js:
  - "7.7"

branches:
  only:
    - master


addons:
  chrome: stable

before_install:
  # starting a GUI to run tests, per https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
  #- "export DISPLAY=:99.0"
  #- "sh -e /etc/init.d/xvfb start"
  #- "npm config set spin false"
  - npm install -g @angular/cli
  - npm install -g firebase-tools

before_script:
  - google-chrome-stable --headless --disable-gpu --no-sandbox --remote-debugging-port=9222 http://localhost:4200 &

script:
  - npm test

after_success:
  - ng build --prod
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change