#.travis.yml

language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master

dist: trusty

addons:
  chrome: stable

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - npm test

after_success:
  - ng build --prod
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change