#.travis.yml

sudo: required
dist: trusty

language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master


addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  # starting a GUI to run tests, per https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "npm config set spin false"

before_script:
  - echo "Starting before script"
  - google-chrome-stable --headless --disable-gpu --no-sandbox --remote-debugging-port=9222 http://localhost:4200
  - echo "Finished before script"

script:
  - echo Beginning Tests
  - npm test
  - echo Finished Tests

after_success:
  - npm install -g @angular/cli
  - npm install -g firebase-tools
  - ng build --prod
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change